### ISSUE TITLE
External node built-ins like fs, path, http

### ISSUE THREAD

**Issue by guoyunhe** [voracious/vite-plugin-externalize-deps#1]
I found here is a rollup plugin https://github.com/Septh/rollup-plugin-node-externals but it doesn't work with Vite. However, I like its feature to external node.js built-in modules, like fs, path, http, etc.

Can you support this feature?

**Comment by davidmyersdev** [comment]
Hi there, @guoyunhe. I'd be open to adding this, but I'll need to get an example node project together first.

**Comment by davidmyersdev** [comment]
@guoyunhe this is now supported in the latest release.
