### ISSUE TITLE
Issue using this with React and Vite 5

### ISSUE THREAD

**Issue by jamesg1** [voracious/vite-plugin-externalize-deps#4]
Hi there,

Thanks for making this plugin. I've been looking for a solution to load React outside of our Vite app bundles as I have a situation where I am loading multiple React Apps (vite bundles) on the page via a CMS. Currently I have duplicated dependencies for React for example so looking to just load it up once.

I was getting this error when I was externalising React and loading it via some UMD scripts on the index.html

`Uncaught TypeError: Failed to resolve module specifier "react/jsx-runtime". Relative references must start with either "/", "./", or "../".`

Any help would be great?

Thanks

**Comment by davidmyersdev** [comment]
Would you mind adding a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this so that I can look into it?
